services:
  # db:
  #   image: pgvector/pgvector:pg17
  #   container_name: pgvector
  #
  #   environment:
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_DATABASE}
  #
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #
  #   networks:
  #     - pet-garden-network

  redis:
    image: redis:7.4-alpine
    container_name: redis

    command: redis-server --requirepass ${REDIS_PASSWORD}

    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - redis_data:/var/lib/redis/data

    networks:
      - pet-garden-network

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #
  #   environment:
  #     MINIO_ROOT_USER: ${S3_USERNAME}
  #     MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
  #
  #   command: minio server /data --console-address ":${S3_PORT}"
  #
  #   ports:
  #     - ${S3_PORT}:${S3_PORT}
  #
  #   healthcheck:
  #     test:
  #       ['CMD', 'curl', '-f', 'http://${S3_HOST}:${S3_PORT}/minio/health/live']
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #
  #   volumes:
  #     - minio_data:/var/lib/minio/data
  #
  #   networks:
  #     - pet-garden-network

  # backend:
  #   build: .
  #   container_name: backend

volumes:
  # pg_data:
  redis_data:
  # minio_data:

networks:
  pet-garden-network:
