services:
  db:
    image: postgres:18-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    ports:
      - ${DB_PORT}:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 30s
      timeout: 20s
      retries: 3

    volumes:
      - pg_data:/var/lib/postgresql/data

    network_mode: bridge

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb

    ports:
      - '8000:8000'

    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

    volumes:
      - chromadb_data:/chroma/chroma

    network_mode: bridge

  redis:
    image: redis:7.4-alpine
    container_name: redis

    command: redis-server --requirepass ${REDIS_PASSWORD}

    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - redis_data:/var/lib/redis/data

    network_mode: bridge

  minio:
    image: minio/minio:latest
    container_name: minio

    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}

    command: minio server /data --console-address ":9001"

    ports:
      - '${S3_PORT}:9000'
      - '9001:9001'

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

    volumes:
      - minio_data:/data

    network_mode: bridge

volumes:
  pg_data:
  redis_data:
  chromadb_data:
  minio_data:
